# Generated by Django 6.0.7 on 2026-07-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysnippet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
