# Generated by Django 6.0.7 on 2026-07-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysnippet', '0004_alter_snippet_created_at_alter_snippet_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
